---
title: "R Notebook"
output: html_notebook
---

devtools::install_github('cttobin/ggthemr')
```{r}
# 加载包
library(tidyverse)
library(jiebaR)
library(wordcloud2)
library(stringr)
library(lubridate)
library(ggplot2)
library(plyr)
library(ggthemes)
library(ggthemr)
library(plotly)
library(htmltools)
```

```{r}
# 读入文件

filePath <- 'weibo/2013783327.txt'
text <- read_lines(filePath,skip=8)


# 预处理
txt <-  text[text!=""]
length(txt)

# 提取微博正文
seq1 <- seq(1,length(txt),by=3)
weibo <- txt[seq1]
zw<- do.call(rbind,lapply(weibo, data.frame))


# 提取发表时间
seq1 <- seq(2,length(txt),by=3)
weibodate <- txt[seq1] %>% str_replace(.,'发布时间：','')

wd<- do.call(rbind,lapply(weibodate, data.frame))

# factor转日期
mydate <- as.Date(as.character.Date(weibodate)) %>% as.data.frame()


# 提取赞转评
seq1 <- seq(3,length(txt),by=3)
weibozzp <- txt[seq1]

zzp <- weibozzp %>% 
  str_replace (.,'点赞数：','') %>%  
  str_replace (.,'转发数：','') %>% 
  str_replace (.,'评论数：','') %>% 
  str_split(.,'\t ',3) %>% 
  as.data.frame() 

zzpt <- t(zzp) 
zzptt <-apply(zzpt,2,function(x)as.numeric(as.character(x))) %>% as.data.frame()

# 合并日期与转赞评
db <- cbind(zzptt,mydate,zw)
names(db) <- c('点赞','转发','评论','date','content')

```

点转赞的折线图
```{r}

# change to long format

db.recent <- db %>% filter(date>'2017-10-1')
ldb <- db.recent %>% 
  gather(key = variable , value = value, -date,-content)


# 动态
a <- plot_ly(ldb, 
        type      = 'scatter', 
        mode      = 'lines', 
        x         = ~date, 
        y         = ~value, 
        color     = ~variable,
        text      = ~paste('date: ', date, '\n',
                           'variable: ', variable, '\n',
                           'value: ', value, '\n' ,
                           '微博: ', content, '\n'),
        hoverinfo = 'text'
        )

# 导出为网页
htmlwidgets::saveWidget(as_widget(a),'index.html')
```


```{r 词云}


# 新建分词器
z <- worker()

# 新词
new_user_word(z, "朱星杰", "n") 
```

```{r}
segWords <- segment(txt,z)
```

```{r}
# 停止词
stopwords <- c("的", "了", "在", "是", "我", "有", "和", "就",  "不", "人", "都", "一", "一个", "上", "也", "很", "到", "说", "要", "去", "你", "会", "着", "没有", "看", "好", "自己", "这",
               "评论","转发","点赞","数","点赞数","发布","时间",'秒拍','流行之王','微博'，'骆明劼',)
segWords <- filter_segment(segWords,stopwords)



# 去除数字、英文、空格
###去除数字和英文
segWords<-gsub("[0-9a-zA-Z]+?","",segWords)


segWords<-str_trim(segWords)#去除空格

# 词频统计
tableWord <- plyr::count(segWords)
write.csv(tableWord,'nid.csv')

# 词云
wordcloud2(tableWord, size = 2, fontFamily = "微软雅黑",  

color = "random-light", backgroundColor = "grey")  

```

